apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wenhant-eks-cluster-east1
  version: "1.30"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1f

iam:
  withOIDC: true

managedNodeGroups:
  - name: sys-nodes2-east1
    instanceType: c5.2xlarge
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 80
    availabilityZones: ["us-east-1f"]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true
        albIngress: true

  - name: efa-compute-ng2-east1
    instanceType: g5.12xlarge
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 300
    efaEnabled: true
    privateNetworking: true
    availabilityZones: ["us-east-1f"]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true
        albIngress: true
