apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wenhant-eks-cluster
  version: "1.30"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
  - us-east-1f

iam:
  withOIDC: true

managedNodeGroups:
  - name: sys-nodes-2
    instanceType: c5.2xlarge
    minSize: 0
    desiredCapacity: 0
    maxSize: 1
    availabilityZones: ["us-east-1a"]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true
        albIngress: true

  - name: efa-compute-ng-2
    instanceType: g5.12xlarge
    minSize: 0
    desiredCapacity: 0
    maxSize: 1
    volumeSize: 300
    efaEnabled: true
    privateNetworking: true
    availabilityZones: ["us-east-1a"]
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true
        albIngress: true
