apiVersion: v1
kind: Pod
metadata:
  name: gen-ai-perf
  labels:
    app: gen-ai-perf
spec:
  containers:
  - name: triton
    image: nvcr.io/nvidia/tritonserver:24.06-py3-sdk
    command: ["sleep", "infinity"]
